spring.application.name=personal-finance
spring.data.mongodb.uri=mongodb+srv://biswasdiganta2001:Riponbiswas1%40@cluster0.vn82wq6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=argos